#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Paulo Alberto Simoes

# Short bio or description (displayed in the header)
description: 
Today, I'm a Cloud Sales Engineer for Oracle. Basically, this means I spend most of my time engineering the best solution to meet the customers' requirements. My principal goal is to help our customers to reach success in their current and future strategic projects. While I work across all of our technologies, my particular focus are on those the leverage the Cloud-Native Architecture, more precisely microservices, containers, and serverless.
My particular passion is work with Open Source Projects (like OpenJDK, FnProject, and Kubernetes) #oss, and Community Development where I really dedicate most of my personal time. Nowadays I am one of the Coordinators of Soujava-Rio Java User Group, Leader of Brazilian Hyperledger Community and I am helping Dockers Community in Rio de Janeiro.
I am close to 20 years of tech market experience with specialization in software engineering, B.Sc. degree in Computer Science by Federal University of the Rio de Janeiro (UFRJ) and MBA in management by Getulio Vargas Foundation (FGV/RJ), with strong expertise in software development, business processes, and integration architectures. Experienced in the telco industry but I had the opportunity to navigate on finance, healthcare, and retail industries.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://s.gravatar.com/avatar/e1cdac1ff443b922baeb45842159a8a6?s=80

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: pasimoes
  instagram:
  linkedin: paulosimoes
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: pasimoes
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
